name: cki
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.3.0+3

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.0
  flutter_mobx: ^2.0.2
  smooth_page_indicator: ^1.1.0
  mobx: ^2.0.5
  webview_flutter: ^3.0.0
  rxdart: ^0.26.0
  shared_preferences: ^2.1.1
  dropdownfield2: ^1.0.7
  carousel_slider: ^4.0.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  font_awesome_flutter: ^10.4.0
  #email_validator:
  #share_extend: ^2.0.0
  firebase_analytics: ^10.4.4
  awesome_notifications: ^0.7.4+1
  flutter_staggered_grid_view: ^0.4.0
  flutter_speed_dial: ^4.6.6
  flutter_launcher_icons: ^0.10.0
  file_picker: ^3.0.0
  open_file: ^3.3.2
  path_provider:
  mysql1: ^0.20.0
  either_dart:
  dartz: ^0.10.1
  get_it: ^7.2.0
  string_validator: ^0.3.0
  fluttertoast: ^8.0.9
  email_validator:
  google_nav_bar: ^5.0.6
  lottie: ^2.3.2
  sizer: ^2.0.15
  dio: ^5.3.2
  url_launcher: ^6.1.10
  google_maps_flutter: ^2.1.0
  location: ^4.4.0
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.1.0 #it helps us to use SVG in our app
  #google_fonts: ^2.3.3 #this allows you to easily use any fonts from fonts.google.com in your Flutter app


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.5
  build_test: ^2.0.0
  mockito: ^5.3.2
  faker: ^2.1.0

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/
    - assets/icons/
    - assets/course/
    - assets/classRoom/
    - assets/books/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: segoeui
      fonts:
        - asset: assets/fonts/segoeui.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  #scripts:dart run build_runner watch --delete-conflicting-outputs
  #dart run flutter_launcher_icons:main -f flutter_launcher_icons*
  #flutter build appbundle --flavor sales -t lib/main_sales.dart
  #keytool -genkey -alias key -keyalg RSA -keypass shareinemor1 -storepass shareinemor1 -validity 10000 -keystore keystore.jks
